# 指定 Docker Compose 文件格式版本（新版本无需指定）
# version: '3.8'

# 定义服务
services:
  # 服务名称，改为更简洁的 py35-jupyter
  py35-jupyter:
    # 构建配置
    build:
      # 构建上下文：Dockerfile 所在的目录
      context: .
      # 指定使用的 Dockerfile 文件名
      dockerfile: Dockerfile

    # 可选：为构建的镜像指定名称和标签
    # 这将决定你运行 `docker images` 时看到的镜像名称
    image: mortalmankind/py35-jupyter:latest # 更新镜像标签以匹配服务名称

    # 可选：为创建的容器指定一个固定的名称
    # 这将决定你运行 `docker ps` 时看到的容器名称
    container_name: py35-jupyter-container # 更新容器名称以匹配服务名称

    # 数据卷挂载：用于在本地主机和容器之间共享文件
    volumes:
      # 将 Docker Compose 文件所在的本地目录 (.) 挂载到容器的 /app 目录
      - .:/app

    # 环境变量：在容器运行时设置
    environment:
      # Python 相关的基本环境变量
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      # 语言和编码设置
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      # 可选：设置时区
      # - TZ=Asia/Shanghai # 示例，请根据需要修改

    # 端口映射
    ports:
      - "8888:8888" # 用于访问 Jupyter Notebook

    # 保持容器的 TTY 和 STDIN_OPEN
    tty: true
    stdin_open: true

    # 重启策略
    restart: unless-stopped

    # 启动命令 (通常在 Dockerfile 的 CMD 中指定)
    # command: [...] # 如果需要覆盖 Dockerfile 的 CMD，请在此处取消注释并添加命令